name: Test and Tag
on: [push]
jobs:
  plex2ifttt_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: gcr.io/cf-networking-images/cfroutesync-integration-test-env
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Check out code
      uses: actions/checkout@v1
    - name: Run tests
      run: ginkgo -r -v .
