name: Test and Tag

on:
  push:
    branches: [ develop ]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Install Ginkgo
      run: |
        go get github.com/onsi/ginkgo/ginkgo
        go get github.com/onsi/gomega/...
    - name: Check out code
      uses: actions/checkout@v1
    - name: Run tests
      run: ginkgo -r -v .

  publish:
    needs: tests
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Check out code
      uses: actions/checkout@v1
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        file: Dockerfile
        push: true
        tags: xanderstrike/plex2ifttt:latest
